export const FETCH_GAME_START = 'FETCH_GAME_START'
export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS'
export const FETCH_GAME_FAILED = 'FETCH_GAME_FAILED'
export const NO_MORE_GAMES = 'NO_MORE_GAMES'

export const SEND_POLL_START = 'SEND_POLL_START'
export const SEND_POLL_SUCCESS = 'SEND_POLL_SUCCESS'
export const SEND_POLL_FAIL = 'SEND_POLL_FAIL'

export const FETCH_POLLS_START = 'FETCH_POLLS_START'
export const FETCH_POLLS_SUCCESS = 'FETCH_POLLS_SUCCESS'
export const FETCH_POLLS_FAIL = 'FETCH_POLLS_FAIL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'
